"""create_currency_conversions_table

Revision ID: 2feb505baf4f
Revises: c5436c26ee39
Create Date: 2026-06-23 10:09:38.459515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2feb505baf4f'
down_revision: Union[str, Sequence[str], None] = 'c5436c26ee39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('result', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_conversions_from_currency'), 'currency_conversions', ['from_currency'], unique=False)
    op.create_index(op.f('ix_currency_conversions_id'), 'currency_conversions', ['id'], unique=False)
    op.create_index(op.f('ix_currency_conversions_to_currency'), 'currency_conversions', ['to_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_conversions_to_currency'), table_name='currency_conversions')
    op.drop_index(op.f('ix_currency_conversions_id'), table_name='currency_conversions')
    op.drop_index(op.f('ix_currency_conversions_from_currency'), table_name='currency_conversions')
    op.drop_table('currency_conversions')
    # ### end Alembic commands ###
