"""create_currency_rates_table

Revision ID: c5436c26ee39
Revises: 612ffda34f94
Create Date: 2026-06-23 10:03:30.967284

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c5436c26ee39"
down_revision: str | Sequence[str] | None = "612ffda34f94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
