"""create_currency_rate_history_table

Revision ID: cf7051e7f1e3
Revises: d20128b2a3d7
Create Date: 2026-06-23 14:37:34.945292

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cf7051e7f1e3'
down_revision: str | Sequence[str] | None = 'd20128b2a3d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_rate_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("target_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_currency_rate_history_base_currency"),
        "currency_rate_history",
        ["base_currency"],
        unique=False,
    )
    op.create_index(
        op.f("ix_currency_rate_history_id"),
        "currency_rate_history",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_currency_rate_history_target_currency"),
        "currency_rate_history",
        ["target_currency"],
        unique=False,
    )
    op.create_index(
        op.f("ix_currency_rate_history_timestamp"),
        "currency_rate_history",
        ["timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_currency_rate_history_timestamp"),
        table_name="currency_rate_history",
    )
    op.drop_index(
        op.f("ix_currency_rate_history_target_currency"),
        table_name="currency_rate_history",
    )
    op.drop_index(
        op.f("ix_currency_rate_history_id"),
        table_name="currency_rate_history",
    )
    op.drop_index(
        op.f("ix_currency_rate_history_base_currency"),
        table_name="currency_rate_history",
    )
    op.drop_table("currency_rate_history")
    # ### end Alembic commands ###
