"""create_favorite_pairs_table

Revision ID: d20128b2a3d7
Revises: dc82eeda16b9
Create Date: 2026-06-23 13:30:27.393532

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d20128b2a3d7"
down_revision: str | Sequence[str] | None = "dc82eeda16b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("target_currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "base_currency",
            "target_currency",
            name="uq_user_favorite_pair",
        ),
    )
    op.create_index(
        op.f("ix_favorite_pairs_base_currency"),
        "favorite_pairs",
        ["base_currency"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_pairs_id"), "favorite_pairs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_favorite_pairs_target_currency"),
        "favorite_pairs",
        ["target_currency"],
        unique=False,
    )
    op.create_index(
        op.f("ix_favorite_pairs_user_id"),
        "favorite_pairs",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorite_pairs_user_id"), table_name="favorite_pairs")
    op.drop_index(
        op.f("ix_favorite_pairs_target_currency"), table_name="favorite_pairs"
    )
    op.drop_index(op.f("ix_favorite_pairs_id"), table_name="favorite_pairs")
    op.drop_index(op.f("ix_favorite_pairs_base_currency"), table_name="favorite_pairs")
    op.drop_table("favorite_pairs")
    # ### end Alembic commands ###
