"""add_user_id_to_currency_conversion

Revision ID: dc82eeda16b9
Revises: 2feb505baf4f
Create Date: 2026-06-23 10:19:26.492181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc82eeda16b9'
down_revision: Union[str, Sequence[str], None] = '2feb505baf4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_conversions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_currency_conversions_user_id'), 'currency_conversions', ['user_id'], unique=False)
    op.create_foreign_key('currency_conversions_user_id_fkey', 'currency_conversions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('currency_conversions_user_id_fkey', 'currency_conversions', type_='foreignkey')
    op.drop_index(op.f('ix_currency_conversions_user_id'), table_name='currency_conversions')
    op.drop_column('currency_conversions', 'user_id')
    # ### end Alembic commands ###
